### ISSUE TITLE
pretty diff viewer

### ISSUE THREAD

**Issue by adamdecaf** [nabla-c0d3/trust_stores_observatory#5]
From https://github.com/nabla-c0d3/trust_stores_observatory/issues/4 it'd be handy to show diffs between yaml files. That way it's a bit more apparent which CA's were removed, added, etc between runs.

**Comment by nabla-c0d3** [comment]
I tried implementing this using `difflib` (https://docs.python.org/3.6/library/difflib.html) but the result is not as good as just using the `diff` command line tool. 
I actually don't think we can have something better than `diff`; one of the reasons I picked YAML was so that it would be easy to diff two stores.

**Comment by adamdecaf** [comment]
Using `diff` is fine, but that probably forces us to sort the yaml. Otherwise there could be diffs just from line noise.

**Comment by nabla-c0d3** [comment]
Yeah, the YAMLs are always sorted by the subject name in this project.
