### ISSUE TITLE
Parse blacklisted.certs to populate the blocked_certificates entry of the Java store

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/trust_stores_observatory#8]
The file at `/lib/security/blacklisted.certs` contains the SHA-256 hash of blacklisted CA certificates. We should parse that to store it in the Java store's YAML file.

**Comment by nabla-c0d3** [comment]
@RaheelaKhan1172 It would assume that the blacklisted certificates are already available in ./certificates (which is probably true as we have the blacklisted certs from the other stores already). If a certificate isn't there, we have to find first and add it ./certificates. After that, it's easy to look them up using the fingerprint.
@adamdecaf There's a field in the YAML file for `blocked_certificates`.

**Comment by adamdecaf** [comment]
You could always try and search a few of the certificate sites too.

- https://crt.sh/?q=19400BE5B7A31FB733917700789D2F0A2471C0C9D506C0E504C06C16D7CB17C0
- https://censys.io/certificates/19400be5b7a31fb733917700789d2f0a2471c0c9d506c0e504c06c16d7cb17c0

**Comment by adamdecaf** [comment]
Which certs were missing? Could you paste their crt.sh or censys.io links?

**Comment by nabla-c0d3** [comment]
You should not edit the YAML files as they are auto-generated when running `python main.py --refresh`. 

However when a `--refresh` is done, you should parse the blacklist and look for each fingerprint in the local repository (using the `lookup_certificate_with_fingerprint()` method), and then add them to the list of `blocked_certificates` for the Java `TrustStore`; this will put the proper fingerprint and subject name in the YAML file.

If the actual certificates are not in `./certificates`, this whole process will fail which is why they need to be added first (as PEM files).

**Comment by RaheelaKhan1172** [comment]
Ack, I re-read my comment and realize how confusing it is ( I'm going to blame that on not feeling well these past few days ) 

What I meant to say was: 
inside `java_store.py`, when I'm parsing the trusted certs, I parsed `blacklisted.certs` as well.
The blacklisted certs go through the same cleansing that the trusted certs go through, so a run of `python main.py --refresh` updates the YAML file ( if there is a change ) and adds in the section for the blacklisted certs with the fingerprint and subject name ( the ones that are in the `/certificate` have a subject name, but the ones that are not in the repo yet only the fingerprint without a subject name ): 
<img width="874" alt="screen shot 2018-04-15 at 12 13 05 pm" src="https://user-images.githubusercontent.com/13926056/38782315-6a735f9c-40a6-11e8-97f9-6c1a8ad2f66f.png">

now, I know which ones are missing, so I manually find and add the certificate as a PEM file to `/certificates`. Refreshing again: 
<img width="775" alt="screen shot 2018-04-15 at 12 47 07 pm" src="https://user-images.githubusercontent.com/13926056/38782624-388d6f86-40ab-11e8-8b77-a74f9fbd24a6.png">

ta-da! All is well and good now-- BUT, I had to manually add the PEM file inside `/certificates` for the certs that were not in the repo. I was wondering if adding the missing certificates inside that repository is okay?

**Comment by RaheelaKhan1172** [comment]
@adamdecaf the missing certs: 
http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/07d73060e0da/src/share/lib/security/blacklisted.certs.pem#l124 

http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/07d73060e0da/src/share/lib/security/blacklisted.certs.pem#l82

http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/07d73060e0da/src/share/lib/security/blacklisted.certs.pem#l166
http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/07d73060e0da/src/share/lib/security/blacklisted.certs.pem#l208
http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/07d73060e0da/src/share/lib/security/blacklisted.certs.pem#l692
http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/07d73060e0da/src/share/lib/security/blacklisted.certs.pem#l642

the top ones are from the development kit instead of jre but I used openssl to verify to fingerprint of the certificates with the one from `blacklisted.certs` and the prints matched

**Comment by nabla-c0d3** [comment]
@RaheelaKhan1172 Yes adding the missing certificates manually to `./certificates` is the right way to go here. ;)
